ffi/ffi

- lib/ffi/autopointer.rb
- lib/ffi/library.rb
- lib/ffi/struct_layout_builder.rb
- lib/ffi/types.rb
````
ffi.git master $ yardoc
[warn]: @param tag has unknown parameter name: [] 
in file `lib/ffi/types.rb' near line 161
[warn]: @param tag has unknown parameter name: cname 
in file `lib/ffi/library.rb' near line 317
[warn]: @param tag has unknown parameter name: type 
in file `lib/ffi/library.rb' near line 317
[warn]: @param tag has unknown parameter name: name 
in file `lib/ffi/library.rb' near line 368
[warn]: @param tag has unknown parameter name: params 
in file `lib/ffi/library.rb' near line 368
[warn]: @param tag has unknown parameter name: ret 
in file `lib/ffi/library.rb' near line 368
[warn]: @param tag has unknown parameter name: [] 
in file `lib/ffi/library.rb' near line 407
[warn]: @param tag has unknown parameter name: ptr 
in file `lib/ffi/autopointer.rb' near line 189 …
```
> fix yard doc warnings

- Rakefile
The clean task allready does pattern interpretation.
> Simplify clean list and add libtest build files.

- Rakefile
- appveyor.yml
- libtest/FunctionTest.c
- libtest/VariadicTest.c
- spec/ffi/fixtures/ClosureTest.c
- spec/ffi/fixtures/FunctionTest.c
- spec/ffi/rbx/attach_function_spec.rb
This is an extended Version of #449 . It is not ready to merge, because not all ruby versions pass the tests. I'll debug the issues and update this PR accordingly.
> Add appveyor.yml for ci-tests on Windows.

- lib/ffi/autopointer.rb
- lib/ffi/enum.rb
- lib/ffi/pointer.rb
- lib/ffi/tools/types_generator.rb
- lib/ffi/types.rb
* fix some YARD syntax errors
* break some monster lines into shorter
* get rid of some empty (but containing blanks) lines
> minor documentation and code style improvements

- .travis.yml
Reverts ffi/ffi#497
more complete version included in #495
> Revert "Switch to using container-based Travis where possible"

- lib/ffi/enum.rb
- lib/ffi/library.rb
- spec/ffi/bitmask_spec.rb
- spec/ffi/fixtures/BitmaskTest.c
Adds suggestion https://github.com/ffi/ffi/issues/570.
> Added support for Bitmask.

- Gemfile
- ffi.gemspec
> Bump rake-compiler-dock dependency to add cross ruby-2.5 support

- .travis.yml
- Rakefile
- appveyor.yml
- ext/ffi_c/libffi.bsd.mk
- ext/ffi_c/libffi.darwin.mk
- ext/ffi_c/libffi.mk
- ffi.gemspec
- spec/ffi/callback_spec.rb
See the single commits for dedicated description. This fixes travis-ci and appveyor errors among other issues. Appveyor should be enabled for this repository, to include it's Windows tests for pull requests.
> Various fixes and more deterinistic gem packaging

- lib/ffi/library.rb
I got a warning. I fixed it.
> /var/lib/gems/2.5.0/gems/ffi-1.9.18/lib/ffi/library.rb:347: warning: assigned but unused variable - s
> suppress unused variable warning

- README.md
This PR changes the build badges to SVG for sharper readability ✨
> README: SVG badge for Travis

- bench/bench_helper.rb
> Fix path to libtest in benchmarks

- .travis.yml
- Rakefile
- bench/bench_helper.rb
- bench/bench_memptr_alloc.rb
- ext/ffi_c/extconf.rb
- lib/ffi.rb
- spec/ffi/embed-test/ext/extconf.rb
- spec/ffi/long_double_spec.rb
- spec/ffi/number_spec.rb
- spec/ffi/spec_helper.rb
- spec/ffi/struct_spec.rb
From https://github.com/ffi/ffi/pull/755#issuecomment-605619633
To fix the benchmarks we need fixes in TruffleRuby FFI's backend, so skip them for now.
> Fix remaining issues to make TruffleRuby pass the CI

- .github/workflows/ci.yml
- .travis.yml
- Rakefile
- bench/bench_getlogin.rb
- bench/bench_gettimeofday.rb
- bench/bench_getuid.rb
- bench/bench_helper.rb
- bench/bench_math.rb
- bench/bench_memptr_alloc.rb
- bench/bench_umask.rb
- ext/ffi_c/extconf.rb
- lib/ffi.rb
- spec/ffi/embed-test/ext/extconf.rb
- spec/ffi/long_double_spec.rb
- spec/ffi/number_spec.rb
- spec/ffi/spec_helper.rb
- spec/ffi/struct_spec.rb
See #760.
Needs #761 to be merged first, as it includes those commits too so CI runs on TruffleRuby as well.
> Use GitHub Actions for CI

- spec/ffi/struct_spec.rb
refs https://github.com/jruby/jruby/pull/6406
> uncomment specs on jruby

- ext/ffi_c/Function.h
- ext/ffi_c/MemoryPointer.h
- ext/ffi_c/Pointer.h
> Remove win32/stdbool.h

- README.md
This is coming up more as people are experimenting with the HEAD of repos trying to get Apple Silicon support working. Example: https://github.com/grpc/grpc/issues/25669#issuecomment-796563819
> Update README with instructions for submodules

- lib/ffi/data_converter.rb
> Fix typo in data_converter.rb

- ext/ffi_c/Variadic.c
The old untyped DATA API is soft deprecated and this new one open the door to write barriers, compaction, memsize etc.
NB: As mentioned in https://github.com/ffi/ffi/pull/991, I'm trying to do the smallest changes possible so that it's easier to spot if I made a mistake.
> Convert FFI::VariadicInvoker to TypedData

- ext/ffi_c/LastError.c
> Convert FFI::ThreadData to TypedData

- ext/ffi_c/Struct.c
> Convert FFI::Struct::InlineArray to TypedData

- ext/ffi_c/Variadic.c
> Implement Write Barrier and dsize for FFI::VariadicInvoker

- ext/ffi_c/StructByValue.c
> Implement Write Barrier and dsize for FFI::StructByValue

- ext/ffi_c/AbstractMemory.c
- ext/ffi_c/AbstractMemory.h
- ext/ffi_c/Buffer.c
- ext/ffi_c/MemoryPointer.c
- ext/ffi_c/Pointer.c
- ext/ffi_c/Variadic.c
This is now possible with new typed data objects.
> Use type checking by TypedData and remove duplocated check by rb_obj_is_kind_of

- ext/ffi_c/Types.h
> Remove enum CHAR_ARRAY

- lib/ffi/library.rb
- lib/ffi/types.rb
For better readability.
And add some comments.
> Move typedef, type_find and related methods around

- .github/workflows/ci.yml
using macos-14; and pin x86_64-darwin to macos-13
> CI: add arm64-darwin coverage

- Gemfile
- spec/env/Dockerfile.centos
- spec/env/Dockerfile.debian
.. since it otherwise disturbs parallel build with rake gem:native
> Install bigdecimal unconditional

- .github/workflows/ci.yml
- Gemfile
- Rakefile
> Add ruby-3.4 native gem

- .github/workflows/ci.yml
This fixes a compilation issue with clang 17 and macOS: https://github.com/libffi/libffi/pull/857
Details: https://github.com/libffi/libffi/releases/tag/v3.4.7
> Update to libffi v3.4.7 + patch

- .github/workflows/ci.yml
- Gemfile
This updates to the latest tagged version.
> Update libffi to v3.4.8
