lib/ffi/struct.rb
Some libraries emulate a class hierarchy using structures full of pointers to functions
=> Added an example for structures containing pointers to functions

ext/ffi_c/libffi/src/x86/win32.S
This fixes an issue when building a 32-bit ffi with Visual Studio. See also https://github.com/atgreen/libffi/issues/77.
=> Add brackets around FORCEFRAME.

lib/ffi.rb
This is necessary to differentiate between 2.1.x and 2.2.1 ruby version
patterns. The pattern is also more accurately reflects the intention.
refs #419
=> Anchor ruby version patterns to start of line

ext/ffi_c/MethodHandle.c, ext/ffi_c/StructLayout.c, ext/ffi_c/extconf.rb
This allows users to provide their own version of libffi instead of always using the bundled version. Newer libffi also implies linking against a DLL on Windows, but we currently link statically for the extension.
=> Fix compatibility with newer libffi on Windows/MSVC

lib/ffi/platform.rb
We have some other platform checker methods but none for Solaris. This just adds FFI::Platform.solaris? to the bunch.
=> Add FFI::Platform.solaris? singleton method

Gemfile, Rakefile, ffi.gemspec
[rake-compiler-dock](https://github.com/larskanis/rake-compiler-dock) makes building Windows gems faster and with little to no setup compared to [rake-compiler-dev-box](https://github.com/tjschuck/rake-compiler-dev-box). A simple 'rake gem:windows' is usually enough.
The build is successfully tested on Linux and Windows. I tested all resulting gems on RubyInstaller versions 2.1.4-x64, 2.2.1-x86 and 2.2.1-x64 on Windows-7. However building on Windows requires UNIX end of line characters. So git should be used like this:
``` sh
git clone -n https://github.com/ffi/ffi
cd ffi
git config core.autocrlf false
git checkout add-rake-compiler-dock -f
rake gem:windows
```
The cross ruby versions used by gem:windows are not passed to the container, so the rake-compiler-dock's defaults are used, which …
=> Simplify cross build tasks and add rake-compiler-dock for building Windows binary gems.

Gemfile, ffi.gemspec
Nothing really important, but version 0.4.0 adds OS-X support, some automatic handling of boot2docker and better diagnosis.
=> Update version of rake-compiler-dock to 0.4.0.

ext/ffi_c/MethodHandle.c
=> methodHandleParamTypes needs to refer to valid memory after rbffi_MethodHandle_Init

spec/ffi/fixtures/FunctionTest.c, spec/ffi/fixtures/PipeHelper.h, spec/ffi/fixtures/PipeHelperPosix.c, spec/ffi/fixtures/PipeHelperWindows.c, spec/ffi/function_spec.rb
This is my attempt to resolve the issue. It is WIP, because it's missing a Windows part.
It tests for concurrency instead of timing. It however has a timeout, so that the test doesn't hang in
a failure condition.
This fixes: https://github.com/ffi/ffi/pull/406
=> Fix test for :blocking=>true with a sleep()-less version.

lib/ffi/struct.rb, spec/ffi/struct_spec.rb
On ruby 2.1.8, this code is fail. (2.1.7 is success)
```ruby
require 'ffi'
class Foo < FFI::Struct
layout foo: :bar
end
```
```
.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/ffi-1.9.10/lib/ffi/struct.rb:344:in `hash_layout': Ruby version not supported (RuntimeError)
```
And current ffi testing code, skip this check since this change https://github.com/ffi/ffi/commit/f75b924ff3abd4c80c66111f1f9c2bbeeb70a171#diff-83f16e6ed1c44a9ced98f69d4139c564
```ruby
"2.1.8" =~ /1\.8\.*/ #=> 2
"2.1.8" =~ /1.8.*/ #=> 2
```
I expect to work `hash_layout` on ruby 2.1.8
=> Support ruby 2.1.8

Rakefile, ext/ffi_c/AbstractMemory.c, ext/ffi_c/Buffer.c, ext/ffi_c/MethodHandle.c, ext/ffi_c/Pointer.c
Context
----------
I have been auditing some third-party Gems for memory errors (such as those addressed by 098dcfba). 
Change
-----------
While I was reading through this codebase, I found a few typos and fixed them up.
=> Typo Fixes

ext/ffi_c/libffi/src/mips/ffi.c
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.
=> Refactoring conditional directives that break parts of statements.

ext/ffi_c/rbffi_endian.h
for x86 and x86_64, we don't have any other host arch btw. yet.
=> Haiku endianness fix

ext/ffi_c/Function.c, ext/ffi_c/MethodHandle.c, ext/ffi_c/compat.h
it seems like the ruby authors do not intend for this to be an external
API.
closes #489
=> remove RB_GC_GUARD_PTR references

.travis.yml
This makes the CI process a bit faster and a bit less resource
intensive. OS X builds run as usual.
=> Switch to using container-based Travis where possible

.travis.yml, Gemfile, Rakefile, ffi.gemspec
ruby-2.2.4 and ruby-2.1.10 are not yet available for OSX on travis, so that I used the latest versions, that are available on both platforms.
This includes #493 .
=> Update for ruby-2.3 cross build and travis-ci

ext/ffi_c/Call.c, ext/ffi_c/Call.h, ext/ffi_c/Variadic.c, spec/ffi/fixtures/FunctionTest.c, spec/ffi/variadic_spec.rb
As reported in #488, `blocking: true` does not work for varargs calls.
I’ve gotten it working by:
- Adding a unit test based on the “can wrap a blocking function” spec in `function_spec.rb`
- Making a typedef and a few functions in `Call.c` public
- Calling those functions in `Variadic.c` if `HAVE_RB_THREAD_CALL_WITHOUT_GVL` is defined.
This makes `blocking: true` work, and the unit test pass, on modern Rubies. Rubies that require more work to support `blocking: true` will get the old behaviour.
=> Support blocking: true for varargs calls

lib/ffi/library.rb, spec/ffi/library_spec.rb
This seems to fix scenarios where the library is provided via a symbol and adds a test for this condition.
=> fix library loading by symbol with test

ffi.gemspec
```console
$ gem build ffi.gemspec
WARNING:  WARNING: license value 'BSD' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
```
=> Use a standard spfx license

lib/ffi/pointer.rb, spec/ffi/pointer_spec.rb
This adds `Pointer#to_ptr`. It's there in JRuby, and particularly useful to assign struct pointers that 
can possibly be `NULL` to `:pointer` fields, i.e.:
```ruby
struct_or_null = ...
other_struct[:pointer_field] = struct_or_null.to_ptr
```
It turns out that the `ffi` gem let's you assign structs directly, without calling `to_ptr`. However, the
call is necessary in JRuby, BTW.
=> Add Pointer#to_ptr

ext/ffi_c/AbstractMemory.c, lib/ffi/pointer.rb, spec/ffi/rbx/memory_pointer_spec.rb
Similar to #472, but a cleaner and more general approach, IMHO.
These methods are especially useful for writing and reading to pointers of typedef'd types, such
as `size_t`.
=> Add AbstractMemory#get and AbstractMemory#put

Gemfile
Ruby 2.4 requires rake-compiler-dock v0.6.0.
Moreover it should always use latest one because of tracking latest rubies.
* Merge this pull request
* run `bundle update` to update the latest rake-compiler-dock, which should support latest Ruby
* bump the version (1.9.14 is already released. it needs to use new one)
* release Unix version with `rake release` or something usual.
* run `bundle exec rake gem:windows`
* It needs docker. see https://github.com/rake-compiler/rake-compiler-dock#installation for the detail
* On macOS,  `bundle exec rake gem:windows MACHINE_DRIVER=xhyve` is easy because it doesn’t need virtualbox
* gem push pkg/ffi-1.9.15-x86-mingw32.gem
* gem push pkg/ffi-1.9.15-x64-mingw32.gem
=> use latest rake-compiler-dock

ext/ffi_c/DynamicLibrary.c
According to [1] the flag LOAD_WITH_ALTERED_SEARCH_PATH should be used with absolute paths only. It has the effect, that the path of the DLL to be loaded is temporary added to the search path, so that dependent DLLs in the same directory can be found and loaded implicit.
However for relative paths the standard LoadLibrary() search order should be used, because the behaviour of LOAD_WITH_ALTERED_SEARCH_PATH isn't defined for relative paths. In practice (on Windows 10) relative paths to Windows system DLLs do work, so that the library is loaded,
but DLLs in other search paths are not found, when this flag is set.
Ruby's fiddle library uses LoadLibrary without flags in both cases.
[1]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms684179(v=vs.85).aspx
=> Avoid undefined behaviour of LoadLibrary() on Windows.

ext/ffi_c/DynamicLibrary.c, ext/ffi_c/extconf.rb, ffi.gemspec
* Specify the latest rake-compiler and rake-compiler-dock in gemspec
* Fixes undefined reference for `PathIsRelativeA`
I've confirmed that `bundle exec rake gem:windows` generates fat gems:
```log
% bundle exec rake gem:windows
% ls pkg
ffi-1.9.17-x64-mingw32     ffi-1.9.17-x86-mingw32.gem
ffi-1.9.17-x64-mingw32.gem ffi-1.9.17.gem
ffi-1.9.17-x86-mingw32
```
=> Tweaks for cross compiling with MSYS2 toolchain

ext/ffi_c/AbstractMemory.c
This fixes #547. It is inspired by https://github.com/ruby/ruby/commit/a1a237fb36d4b78548d2aa94f03a6c460e50b4a7 (also used in https://github.com/ruby/ruby/blob/ff3496b0116ed2ed589d000b7bfca3d8288b009c/ext/json/fbuffer/fbuffer.h#L28-L35).
*I'm not sure if defining of `RB_OBJ_CLASSNAME` is needed here.*
Currently, there's ruby `>= 1.8.7` `required_ruby_version` in gemspec. To support 1.8.7 we need to remove `rb_sprintf` usage also.
It will be nice to decide how to proceed before new version will be released:
1. drop < 2.0 support (change `required_ruby_version` to '>= 2.0.0' in gemspec)
2. merge this and support Ruby >= 1.9.3 (change `required_ruby_version` to '>= 1.9.3' in gemspec)
3. merge this + remove usage of `rb_sprintf` and support => 1.8.7
=> Use PRIsVALUE shim when not available for Ruby 1.9.3 compatibility.

.travis.yml, Rakefile, ffi.gemspec, lib/ffi/struct.rb, spec/ffi/struct_spec.rb
[It seems that Ruby FFI does not support Ruby 1.8.7 and earlier.](https://github.com/ffi/ffi/pull/479/files)
I propose that required ruby version will be specified to `gemspec` file.
Thanks.
=> Drop Ruby 1.8.7 support

lib/ffi/platform.rb
I'm not sure if anything else needs updated to work with MSYS2, but these changes made it work in an install of MSYS2 with the Ruby 2.3.3 package installed.
=> Add support for MSYS2

ext/ffi_c/Platform.c, lib/ffi/platform.rb
Linux appears to report as 'sparc64' rather than 'sparcv9' when running on the same CPU. Since the CPU features are the same, normalize to 'sparcv9' to keep things simple.
=> Normalize sparc64 to sparcv9.

Rakefile
In Windows there's no `/dev/null` and it causes error "The System cannot find the path specified". Also in Windows there's no native `which` and it works only because it's included in DevKit.
This Ruby implementation should correctly work for all platforms.
=> Use Ruby implementation for `which`

.travis.yml
Updated to latest ruby versions, also removed unnecessary quotes.  Ruby-2.4.2 on OSX needs to be build with xcode9.1.  Ruby-2.0 and earlier fail to build if xcode9.1 is set on all builds, so I only applied it to the 2.4.2 builds.
=> update travis for latest versions

lib/ffi/library.rb
Currently any projects relying on package manager MacPorts and Fink unable to load libraries due to search path. By adding search path for `/opt/local/lib` will resolve this issue and many other ruby libraries using FFI.
Error example:
`LoadError: Could not open library 'glib-2.0': dlopen(glib-2.0, 5): image not found.`
=> Adding MacPorts,Fink,etc search path to /opt/local/lib

lib/ffi/pointer.rb
The documentation of Pointer#read_array_of_type states that I should pass `:get_uint8` to it, but actually it should be `:read_uint8`, because `:get_uint8` would fail with `ArgumentError: wrong number of arguments (given 0, expected 1)` 
This PR is actually fixes #266 which is closed, but not fixed (from 2013!)
=> Replaced :get_uint8 with :read_uint8 in Pointer#read_array_of_type documentation

lib/ffi/pointer.rb, spec/ffi/pointer_spec.rb
The following example that is written in comments of Pointer#write_array_of_type did not work.
ptr.write_array_of_type(TYPE_UINT8, :put_uint8, [1, 2, 3 ,4])
I fixed it and made test for it.
Would you consider merging these commits?
=> Pointer#write_array_of_type did not work

ext/ffi_c/LastError.c
Under cygwin both errno and GetLastError are needed. This
adds second getter named #win_error:
Linux
FFI::LastError.error     == errno
FFI::LastError.win_error == NoMethodError
Windows
FFI::LastError.error     == GetLastError
FFI::LastError.win_error == GetLastError
Cygwin
FFI::LastError.error     == errno
FFI::LastError.win_error == GetLastError
Fixed #632
=> Add FFI::LastError.win_error

.travis.yml
This PR is here to keep the Travis configuration file simpler.
- `gem install bundler` is done after rvm has installed a bundler (this is true for each of the Rubies in the matrix)
- Remove outdated `sudo: false` Travis directive
=> CI: Skip superfluous gem install bundler

.travis.yml
This PR reduces the size of the CI matrix by removing `system`.
- its file location for gems is not even writable, so it fails to install
- it does not represent any new Ruby version which does not already exist in the matrix
=> CI: Drop "system" ruby

.travis.yml, spec/env/Dockerfile.armhf, spec/env/Dockerfile.powerpc
CI testing is currently done on Windows-x86, Windows-x64, Linux-x86_64 and MacOS-x86_64.
This adds PPC64le and ARMv7 by using docker and qemu.
This also adds JRuby and Truffleruby, so that we notify the differences to them. They currently fail, but the aim is to fix JRuby and Truffleruby support in the future.
=> Add tests on armhf and ppc64le linux, JRuby and Truffleruby on Travis-CI

bench/bench_FFFrV.rb, bench/bench_FrV.rb, bench/bench_IIIIIIrV.rb, bench/bench_IIIrV.rb, bench/bench_IrV.rb, bench/bench_VrI.rb, bench/bench_VrV.rb, bench/bench_closure_IIIrV.rb, bench/bench_closure_IrV.rb, bench/bench_closure_VrV.rb, bench/bench_enum.rb
Removes the `ruby/dl` references from the benchmarks so they run.
=> make benchmarks run

.gitmodules, Gemfile, Rakefile, appveyor.yml, ext/ffi_c/extconf.rb, ffi.gemspec, spec/ffi/fixtures/PipeHelperWindows.c
This makes sure that we run tests with system libffi and with bunded libffi on Appveyor (Windows build). The specs fail on [current libffi master branch](https://github.com/libffi/libffi/tree/8fa88373a1d433c675b11200ccd58418e91f81e4) due to broken stdcall to closures. This can be seen [here](https://ci.appveyor.com/project/larskanis/ffi/builds/21853146/job/qjlf1yrp0o5tpesx).
The failing stdcall issue is fixed by [this PR](https://github.com/libffi/libffi/pull/465). This is why the PR enables a libffi fork temporary.
Fixes #649
=> Add ability to disable or force system libffi and fix stdcall on Win32

README.md
Based on [the comment](https://github.com/ffi/ffi/issues/622#issuecomment-464341759) for issue #622.
Adding information of required packages to the README seems to be sufficient enough action.
=> Update README with information on FreeBSD dependencies using clang.

lib/ffi/pointer.rb, spec/ffi/rbx/memory_pointer_spec.rb
* Like other pointer string methods and usages.
* Fixes #691.
* String#b is available since Ruby 2.0.
=> Fix FFI::Pointer#read_string(0) to return a binary String

README.md
wiki.github.com appears to render an error and the canonical URL for GitHub wikis are not a subdomain but in fact a subdirectory /wiki/
=> Fix wiki links in README

ffi.gemspec
This adds [RubGems metadata](https://guides.rubygems.org/specification-reference/#metadata) to this gem, to make it navigable in RubyGems.org.
=> Add gemspec metadata

spec/ffi/buffer_spec.rb, spec/ffi/callback_spec.rb, spec/ffi/string_spec.rb
Along with my mostly pure-Ruby implementation for TruffleRuby (#660), I discovered a few incompatibilities in TruffleRuby which were not covered by existing specs.
So in this PR, I add specs for previously untested code.
cc @larskanis
=> Add specs for missing cases

ffi.gemspec
In order not to lose any of the links at release, when RubyGems writes them in, again.
=> Complete gemspec metadata

spec/ffi/long_double.rb
It is as the subject.
Refer
ruby/bigdecimal@5337373
=> Fix BigDecimal.new

ext/ffi_c/AbstractMemory.c, ext/ffi_c/Call.c, ext/ffi_c/DynamicLibrary.c, ext/ffi_c/Function.c, ext/ffi_c/Types.c, spec/ffi/string_spec.rb
Ruby 2.7 deprecates taint and it no longer has an effect.
https://bugs.ruby-lang.org/issues/16131
The APIs related to taint cause deprecation warning message and the lack of taint support should not cause a problem in previous Ruby versions.
So I removed that. But if need to taint support that to old versions of Ruby, I will update PR.
=> Remove taint support

spec/ffi/fixtures/GNUmakefile, spec/ffi/fixtures/compile.rb
See the individual commit messages for details.
Part of https://github.com/ffi/ffi/issues/660#issuecomment-603895774
=> A few fixes for the test Makefile

ext/ffi_c/Function.c, ext/ffi_c/MethodHandle.c
```
../../../../ext/ffi_c/Function.c: In function 'callback_prep':
../../../../ext/ffi_c/Function.c:867:5: warning: 'ffi_prep_closure' is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]
```
=> replace ffi_prep_closure with ffi_prep_closure_loc

lib/ffi.rb
JRuby's FFI is almost aligned with the gem via jruby/jruby#5948. This change will allow us to use ffi.rb unmodified.
=> Load JRuby ext under JRuby

Rakefile, lib/ffi.rb
Related to https://github.com/ffi/ffi/pull/747 .
JRuby-9.3 is expected to be fully compatible to this gem's Ruby code. This allows to ship the Ruby library code per platform java gem and add it as a default gem to JRuby.
=> Add ruby source files to the java gem

ext/ffi_c/StructLayout.c, spec/ffi/struct_spec.rb
* Note that the last two of these specs fail on master, so I fixed the C extension to also have this behavior.
Part of https://github.com/ffi/ffi/issues/660#issuecomment-603895774
=> Add checks and specs for writing to inline array and char array fields

lib/ffi.rb, lib/ffi/pointer.rb
Similar logic as for JRuby.
This will only apply for TruffleRuby >= 20.1.0 (not yet released), as versions before don't expect that.
I ran it locally with this and changes in TruffleRuby and all specs passed.
Ref #660
=> Use the Ruby files of the FFI gem on TruffleRuby >= 20.1.0

ext/ffi_c/Function.c, spec/ffi/fixtures/ClosureTest.c, spec/ffi/long_double_spec.rb
It wasn't implemented so far. Such callbacks returned `nan` before.
=> Add long double as callback return value

lib/ffi/struct.rb, spec/ffi/struct_spec.rb
* Fixes https://github.com/ffi/ffi/issues/776
=> Improve check to detect if a module has a #find_type method suitable for FFI

Gemfile
irb-1.1.1 fails on ruby-2.7 with:
```ruby
lars@l1056lx:~/comcard/ffi$  git:(master) 1M 2A irb
Traceback (most recent call last):
7: from /home/lars/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
6: from /home/lars/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
5: from /home/lars/.rvm/gems/ruby-2.7.1/bin/irb:23:in `<main>'
4: from /home/lars/.rvm/gems/ruby-2.7.1/bin/irb:23:in `load'
3: from /home/lars/.rvm/gems/ruby-2.7.1/gems/irb-1.1.1/exe/irb:9:in `<top (required)>'
2: from /home/lars/.rvm/gems/ruby-2.7.1/gems/irb-1.1.1/exe/irb:9:in `require'
1: from /home/lars/.rvm/gems/ruby-2.7.1/gems/irb-1.1.1/lib/irb.rb:12:in `<top (required)>'
/home/lars/.rvm/gems/ruby-2.7.1/gems/irb-1.1.1/lib/irb.rb:12:in `require': cannot load such file -- e2mmap (LoadError)
```
=> Stick to older rubygems-tasks, to avoid dependency to too old irb

ext/ffi_c/Buffer.c, ext/ffi_c/MemoryPointer.c, ext/ffi_c/MethodHandle.c, ext/ffi_c/Pointer.c, ext/ffi_c/compat.h, ext/ffi_c/extconf.rb, lib/ffi/platform.rb
These 5 commits fix various issues that prevent Microsoft Visual Studio 2019 from compiling the ffi bindings. Each commit provides details about the specific issue it is fixing.
=> MSVC 2019 Fixes

ext/ffi_c/FunctionInfo.c, lib/ffi/library.rb, lib/ffi/struct.rb, spec/ffi/callback_spec.rb, spec/ffi/struct_callback_spec.rb
Callbacks returning a :string type were not supported so far. It was possible to define such a callback, but the value returned was NULL in any case. This implementation rejects :string return type of callbacks.
The reason for the reject is the following: In contrast to :string parameters to called functions there is no well defined ownership of the memory of the string returned by callbacks. Instead an explicit FFI::MemoryPointer or similar should be used, which allows to track the validity of underlying memory instead of relying on some Ruby implementation details.
Fixes #751
Alternative to #770
=> [WIP] Reject callback with :string return type

ext/ffi_c/Call.c, ext/ffi_c/Function.c, ext/ffi_c/Thread.c, ext/ffi_c/Thread.h, ext/ffi_c/extconf.rb, spec/ffi/callback_spec.rb, spec/ffi/struct_spec.rb, spec/ffi/variadic_spec.rb
Now that the gemspec requires ruby-2.3 or newer, compatibility code can be removed.
=> Remove code required for ruby prior 2.3

ext/ffi_c/extconf.rb
We use this function since ffi-1.13.0 but didn't test for it.
It seems that MacOS 10.14 ships a libffi which is missing this function (older than 11 years).
On the other hand we don't use ffi_closure_alloc() any longer.
Fixes #785
=> Test for ffi_prep_closure_loc() to make sure we can use this function

bench/bench_time.rb, lib/ffi/platform.rb, spec/ffi/library_spec.rb
ffi-1.13.0 switched FFI::Library::LIBC from msvcrt.dll to ucrtbase.dll as part of #779 in commit c67468366e63bcf84512837384049fbba7e4748c .
As described in #788 ucrtbase.dll has behavioural changes which shouldn't be released as part of a minor version change of ffi. While the change makes sense for mswin, we revert it for mingw.
Fixes #788
=> Revert to msvcrt.dll as LIBC on MINGW

lib/ffi/library.rb, spec/ffi/library_spec.rb
When a library can not be loaded is is tried to be interpret as a loader script.
This failed when the failing library is a binary file and has no valid UTF-8 content.
In this case the original LoadError was hidden.
Open as a binary file fixes this.
Also add a spec for loader script interpretation.
Fixes #792
=> Fix possible UTF-8 error in ffi_lib rescue block

spec/ffi/fork_spec.rb
I forgot about these specs when fixing #621. They should be merged, to verify this use case in the future.
=> Add specs specific to Centos callback bug #621

lib/ffi/platform.rb
"arm64" is only used on MacOS - other platforms call it "aarch64". Since it's the same architectur unify it to "aarch64".
Related to #801
=> Use aarch64 as FFI::Platform::ARCH on MacOS

.appveyor.yml, .travis.yml
See https://github.com/ffi/ffi/issues/760#issuecomment-605897217
We should be able to move the remaining jobs to GitHub Actions as well, but might as well cleanup the redundant ones now.
=> Remove redundant CI jobs

ext/ffi_c/MethodHandle.c
`handle` has memory area allocated in `rbffi_MethodHandle_Alloc()`
https://github.com/ffi/ffi/blob/faae322f74969dfd9a64f767636fea9ed035bf85/ext/ffi_c/MethodHandle.c#L107
And it should be released.
=> Fix memory leak in MethodHandle

ext/ffi_c/AbstractMemory.c, spec/ffi/pointer_spec.rb
This changes array read and write methods to no longer raise a FFI::NullPointerError if there is actually no memory access.
Fixes #305
=> Do NULL pointer check only when array length > 0

spec/ffi/long_double_spec.rb, spec/ffi/rbx/attach_function_spec.rb, spec/ffi/struct_spec.rb
for https://github.com/jruby/jruby/pull/6375
=> jruby fixes

lib/ffi.rb
When running with --disable-gems, JRuby still needs to be able to load FFI from stdlib. Accessing the Gem namespace here requires that gems not be disabled.
This patch uses a simple split and integer comparison to compare the first two digits of the JRuby version with 9.3.
See #763 for the original code.
This patch is necessary for JRuby to fully source the FFI Ruby files from the gem (jruby/jruby#6150). Example failures here are due to the MRI suites running without RubyGems enabled, but they end up needing FFI for internal JRuby functionality.
https://travis-ci.org/github/jruby/jruby/builds/729197020
So close!
=> Check JRuby version without accessing Gem

ext/ffi_c/Pointer.c, spec/ffi/platform_spec.rb, spec/ffi/pointer_spec.rb, spec/ffi/spec_helper.rb, spec/ffi/struct_spec.rb
Also slight clarify documentation on `Pointer#order`, raise on an unknown order, and specify `Platform::BYTE_ORDER` etc.
Working towards https://github.com/oracle/truffleruby/issues/2054.
=> Specify Pointer#order and Struct#order

lib/ffi/platform.rb, spec/ffi/pointer_spec.rb, spec/ffi/struct_spec.rb
Follow-up of https://github.com/oracle/truffleruby/issues/2054.
@larskanis https://github.com/ffi/ffi/blob/234ebce58eb179035c1c0568f198d34b75f7eb90/ext/ffi_c/rbffi_endian.h seems more verbose/complicated than the Ruby code to define these 3 constants, should we remove that file and always let Ruby code define them? The specs already check that LITTLE_ENDIAN is 1234 and BIG_ENDIAN is 4321, so at least that's valid for all platforms tested in CI.
Also the `pack()` check seems more reliable than a series of `#ifdef`.
We still need `unless defined?` checks for JRuby which defines them in the Java extension.
cc @chrisseaton
=> Define endian constants and fix CI on TruffleRuby

ext/ffi_c/Pointer.c, spec/ffi/pointer_spec.rb
Hi, thanks for this great library!
This PR adds a method to tell if the pointer size is bounded.
```ruby
ptr = FFI::Pointer.new(0)
ptr.bounded?              # false
ptr.slice(0, 10).bounded? # true
```
This can be useful for libraries that accept `FFI::Pointer` arguments.
```ruby
def load_image(ptr, ...)
raise "Cannot load image from pointer with unbounded size" unless ptr.bounded?
end
```
=> Adds method to check of pointer size if bounded

ext/ffi_c/AbstractMemory.c, lib/ffi/pointer.rb, spec/ffi/string_spec.rb
* Add specs for FFI::Pointer#write_string and #put_string
* Fixes #805
There was no specs for `write_string` yet, so actually changing as proposed in #805 caused no spec failures.
=> Fix FFI::Pointer#write_string to always terminate with a \0 byte

ext/ffi_c/Pointer.c, lib/ffi/abstract_memory.rb, spec/ffi/pointer_spec.rb
Since size is defined in AbstractMemory, size_limit? should be there as well.
Moving to Ruby code ensures that it works on JRuby and Truffleruby.
=> Move Pointer#size_limit? to AbstractMemory and from C to ruby

spec/ffi/fixtures/compile.rb
Use the workaround from #843 in the specs, so the result matches for arm64 on macOS.
Needed because Ruby versions prior to 3.0 return "arm" instead of "arm64" for `RbConfig::CONFIG['host_cpu']`.
=> Fix specs for Ruby 2.x on darwin-arm64

ext/ffi_c/extconf.rb
Fiddle can crash when used together with ffi and it's builtin libffi. This happens because fiddle is linked to system libffi, but ffi is linked to builtin libffi. Depending on which of these gems is loaded first, they link to the wrong runtime library.
This issue is similar to the issue in nokogiri: https://github.com/sparklemotion/nokogiri/issues/1959
Fixes #835
=> Fix possible segfault in combination with fiddle or other libffi using gems

README.md
Since travis-ci.org will shut down.
=> Move from travis-ci.org to travis-ci.com

ext/ffi_c/AbstractMemory.c, lib/ffi/pointer.rb, spec/ffi/string_spec.rb
.. but add test cases for write_sting semantics.
This reverts commit 2b44904f8323dcad3eaa978c1fd2b5298bd04663, reversing changes made to 2918fdfc7fde6456d5ddc1090a783de0e82d6e39.
Fixes #857
=> Revert "Merge pull request #806 from eregon/fix-write_string"

ext/ffi_c/Variadic.c, spec/ffi/callback_spec.rb, spec/ffi/fixtures/ClosureTest.c
As I explained in https://github.com/ffi/ffi/issues/732#issuecomment-784703145, if you passed callbacks in varargs, a `NULL` pointer would be dereferenced and your program would crash.
I modified `variadic_invoke` to pass proper `callbackParameters` and `callbackCount` to `rbffi_SetupCallParams`, and that seems to fix the problem.
=> Allow to pass callbacks in varargs

ext/ffi_c/Function.c, spec/ffi/async_callback_spec.rb, spec/ffi/function_spec.rb
I found this useful while reviewing datadog/dd-trace-rb#1371 -- we were searching for specs that leaked threads, and saw a "mysterious" thread with no stack that we couldn't exactly point out what created it or why it existed.
By setting a name on the callback thread, it becomes immediately obvious when looking at `Thread.list` what this thread is and where it comes from.
(Thread naming has been around [since Ruby 2.3](https://github.com/ruby/ruby/blob/v2_3_0/NEWS) which means we can do it safely for every supported version)
=> Name the async_cb_thread for easier debugging

CHANGELOG.md, ext/ffi_c/Function.c, spec/ffi/fork_spec.rb
After fork() the dispatcher thread is no longer running, so it needs to be restarted in the child process.
Fixes #884
=> Fix async callbacks in conjunction with fork()

lib/ffi/tools/const_generator.rb, lib/ffi/tools/struct_generator.rb
Right now one can override `gcc` for `types_generator.rb`, but not `const_generator.rb` and `struct_generator.rb`. This PR fixes this.
Related: https://github.com/typhoeus/ethon/issues/186
=> Allow overriding `gcc` with the `CC` env var in `const_generator.rb` and `struct_generator.rb`

ext/ffi_c/extconf.rb
Some versions of Ruby are identifying Apple M1 hosts as 'arm-apple-darwin20.3.0' and others 'aarch64-apple-darwin20.3.0'.
* Ruby 2.6.5 - `RbConfig::CONFIG['host'] == 'arm-apple-darwin20.3.0'`
* Ruby 2.6.7 - `RbConfig::CONFIG['host'] == 'aarch64-apple-darwin20.3.0'`
=> Use arm or aarch64 to identify Apple ARM CPU arch

lib/ffi/library.rb
As the homebrew team discussed in https://github.com/Homebrew/brew/issues/9177 the new library path for homebrew on apple silicon is `/opt/homebrew/lib`. Alongside the PR to support MacPorts https://github.com/ffi/ffi/pull/638 this commits adds support for the new homebrew path.
Fixes #880
=> dynlib support for homebrew 3 on Apple Silicon M1

bench/bench_time.rb, lib/ffi/platform.rb
Take the same approach for detection as used in fiddle:
https://github.com/ruby/ruby/blob/79717f81f8ba24960cca6c934d00c72db64139ed/test/fiddle/helper.rb#L55-L56
=> Fix Windows libc detection for MSYS2-ucrt build

.github/workflows/ci.yml
This is because rubyinstaller-head switched to MINGW-UCRT, so the package prefix is
mingw-w64-ucrt-x86_64
instead of
mingw-w64-x86_64
=> CI: Install libffi which matches running arch

lib/ffi/library.rb
The inclusion of @ioquatix's `ffi-module` gem to a project causes errors loading other ffi gems (such as `rbnacl`) due to the definition of `FFI::Module` which makes `.kind_of?(Module)` equivalent to `.kind_of?(FFI::Module)`.
This change simply changes that lookup to ensure that it is checking against the top-level Module constant.
=> Correct module lookup when including ffi-module

ext/ffi_c/Platform.c
uClibc does not install `gnu/lib-names.h`.
=> Fix build for uClibc

ext/ffi_c/Call.c
=> Keep `LONGDOUBLE_ADJ >= sizeof(long double)`

lib/ffi/tools/const_generator.rb
when using shared tmp dir inside parallel docker containers (same Process id)
you can see errors like below
```ruby
const_generator.rb:136:in ``': Text file busy - /tmp/rb_const_gen_bin_1 (Errno::ETXTBSY)
```
```ruby
const_generator.rb:137:in `unlink': No such file or directory @ apply2files - /tmp/rb_const_gen_bin_1 (Errno::ENOENT)
```
=> fix unlink error 

ext/ffi_c/Pointer.c, spec/ffi/pointer_spec.rb
If the high bit of the address was set this would raise RangeError (bignum too big to convert into long long). This is not uncommon on platforms that use the high bits of pointers for purposes such as pointer authentication (eg arm64 on apple platforms - https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication )
I've not encountered this error directily but I have had reports of it from users with apple M1 hardware
This also now matches Pointer#address which uses ULL2NUM.
=> Fix Pointer#initialize using NUM2LL instead of NUM2ULL

lib/ffi/dynamic_library.rb, lib/ffi/library.rb
* Try every prefix, not just the first one where the file exists.
The first existing file might be for the wrong architecture or have
other issues and cannot be loaded.
* Show which directories were searched in error message.
* Only consider /opt/homebrew/lib on darwin-aarch64.
* Only rescue LoadError and RuntimeError, not Exception.
* Refactor in smaller methods to improve readability.
* Fixes #880.
* Example error message:
`Could not open library 'notexist': notexist: cannot open shared object file: No such file or directory. (LoadError)`
`Could not open library 'libnotexist.so': libnotexist.so: cannot open shared object file: No such file or directory.`
`Searched in <system library path>, /usr/lib, /usr/local/lib, /opt/local/lib`
=> Refactor library lookup

spec/ffi/library_spec.rb
It fails in Macos-12, since that version raises a different error message than Macos-11. On the other hand, linker script emulation seems not to be in use on Macos at all, since Macos uses .dylib file extansion rather than .so.
Fixes #981
=> Skip spec of linker script emulation on Macos

spec/ffi/errno_spec.rb
the latest jruby-head is still cached on GHA, but it should be fixed now.
=> WIP: reenable last error spec

lib/ffi/autopointer.rb
It makes no sense to initialize the base class with a potentially invalid pointer.
Otherwise this PR has no functional impact.
=> Check the pointer in AutoPointer before super

ext/ffi_c/AbstractMemory.c, ext/ffi_c/ArrayType.c, ext/ffi_c/ArrayType.h, ext/ffi_c/Function.c, ext/ffi_c/Function.h, ext/ffi_c/FunctionInfo.c, ext/ffi_c/MappedType.c, ext/ffi_c/MappedType.h, ext/ffi_c/Struct.c, ext/ffi_c/Struct.h, ext/ffi_c/StructByValue.c, ext/ffi_c/StructLayout.c, ext/ffi_c/Type.c, ext/ffi_c/Type.h, ext/ffi_c/Variadic.c, ext/ffi_c/extconf.rb
NB: As mentioned in https://github.com/ffi/ffi/pull/991, I'm trying to do the smallest changes possible so that it's easier to spot if I made a mistake. In this case because of the "inheritance" between types, I had no choice but to convert them all at once.
I'm also not particularly happy to have to expose some of these `data_type_t`, but I followed the existing convention of prefixing them with `rbffi_`.
=> Convert FFI::Type and descendants to TypedData

ext/ffi_c/AbstractMemory.c, ext/ffi_c/AbstractMemory.h, ext/ffi_c/Buffer.c, ext/ffi_c/Call.c, ext/ffi_c/DynamicLibrary.c, ext/ffi_c/Function.c, ext/ffi_c/MemoryPointer.c, ext/ffi_c/Pointer.c, ext/ffi_c/Pointer.h, ext/ffi_c/Struct.c, ext/ffi_c/Types.c
=> Convert FFI::AbstractMemory and descendants to TypedData

ext/ffi_c/Call.c, ext/ffi_c/Function.c, ext/ffi_c/Struct.c, ext/ffi_c/Struct.h, ext/ffi_c/StructLayout.c
=> Convert FFI::Struct to TypedData

ext/ffi_c/DynamicLibrary.c, ext/ffi_c/StructLayout.c
And change a remaining use of TypedData object for completeness even if this code part is commented out.
Ref: #991
=> Convert FFI::DynamicLibrary to TypedData

ext/ffi_c/FunctionInfo.c, spec/ffi/function_type_spec.rb, spec/ffi/spec_helper.rb
=> Implement Write Barrier and dsize for FFI::FunctionType

ext/ffi_c/Type.c
It was missing a `:`
before:
```ruby
>> FFI::Type::Builtin::CHAR
=> #<FFI::Type::Builtin:INT8 size=1 alignment=1>
```
after:
```ruby
>> FFI::Type::Builtin::CHAR
=> #<FFI::Type::Builtin::INT8 size=1 alignment=1>
```
=> Fix `Type#inspect` to properly display the constant name

ext/ffi_c/Function.c, spec/ffi/function_spec.rb
Write barrier protected objects are allowed to be promoted to the old generation,
which means they only get marked on major GC.
The downside is that the RB_BJ_WRITE macro MUST be used to set references,
otherwise the referenced object may be garbaged collected.
This commit also implement a `dsize` function so that these instance report
a more relevant size in various memory profilers. It's not counting everything
because some types are opaque right now, so a larger refactoring would be needed.
=> Implement Write Barrier and dsize for FFI::Function

ext/ffi_c/DynamicLibrary.c, spec/ffi/library_spec.rb
And FFI::DynamicLibrary::Symbol
Write barrier protected objects are allowed to be promoted to the old generation,
which means they only get marked on major GC.
The downside is that the RB_BJ_WRITE macro MUST be used to set references,
otherwise the referenced object may be garbaged collected.
This commit also implement a `dsize` function so that these instance report
a more relevant size in various memory profilers. It's not counting everything
because some types are opaque right now, so a larger refactoring would be needed.
While I was at it, I moved `Symbol.library` into the unused `Symbol.base.rbParent`
which seemed appropriate and saves a pointer.
=> Implement Write Barrier and dsize for FFI::DynamicLibrary

ext/ffi_c/Struct.c, spec/ffi/struct_spec.rb
=> Implement Write Barrier and dsize for FFI::Struct

ext/ffi_c/Struct.c, ext/ffi_c/Struct.h, ext/ffi_c/StructLayout.c, lib/ffi/struct.rb, spec/ffi/struct_spec.rb
And FFI::StructLayout::Field
I had to get rid of the `memset(0)` in `struct_layout_mark` has with Write Barriers it's not guaranteed that the layout will be marked before `fieldName` is moved.
I don't think it was a good fix anyway, it's better to mark these VALUE so the GC pin them. I think we could go back to an `st_table` and mark only the keys with `rb_mark_set`. …
=> Implement Write Barrier and dsize for FFI::StructLayout

ext/ffi_c/AbstractMemory.c, ext/ffi_c/Buffer.c, ext/ffi_c/MemoryPointer.c, ext/ffi_c/Pointer.c, spec/ffi/buffer_spec.rb, spec/ffi/pointer_spec.rb, spec/ffi/rbx/memory_pointer_spec.rb
As well as FFI::MemoryPointer and FFI::AbstractMemory
This commit also implement a dsize function so that these instance report a more relevant size in various memory profilers.
@larskanis I'm curious whether `FFI::AbstractMemory.new` is ever meant to be used? If I make it raise no test fail, and I really don't see what the usage would be. 
I'm tempted to just undefine the allocation function.
=> Implement Write Barrier and dsize for FFI::Pointer

ext/ffi_c/ArrayType.c, ext/ffi_c/DynamicLibrary.c, ext/ffi_c/LastError.c
This commit also implement a `dsize` function so that these instance report a more relevant size in various memory profilers. It's not counting everything because some types are opaque right now, so a larger refactoring would be needed.
=> Implement the last missing Write Barriers and dsize

ext/ffi_c/AbstractMemory.c
This disables AbstractMemory.new, which has no practical use.
As discussed in #1010
=> Remove allocator of AbstractMemory

gen/Rakefile
Ruby 3 changed the 'mode' argument from an option hash to keyword argument.  This change is backwards-compatible with Ruby 2.
See: https://github.com/ruby/fileutils/commit/482de6d397742526d1111576e2791f9b7051e3c0
=> Update gen/Rakefile for Ruby 3 compat

ext/ffi_c/ArrayType.c, ext/ffi_c/Buffer.c, ext/ffi_c/DynamicLibrary.c, ext/ffi_c/Function.c, ext/ffi_c/FunctionInfo.c, ext/ffi_c/MappedType.c, ext/ffi_c/Pointer.c, ext/ffi_c/Struct.c, ext/ffi_c/StructByValue.c, ext/ffi_c/StructLayout.c, ext/ffi_c/Variadic.c, ext/ffi_c/compat.h, ext/ffi_c/extconf.rb
This allows to relocate all FFI objects.
Also remove marking of `StructLayout->cache_row` in favour of clearing it at `GC.compact` only.
=> Make FFI classes GC.compact friendly

ext/ffi_c/Type.c
It is not used in C or Ruby code.
=> Remove unused FFI::SizeTypes

ext/ffi_c/AbstractMemory.c, ext/ffi_c/Struct.c
RARRAY_PTR is bad for GC performance as it exposes the internal buffer of the array meaning that the array becomes write barrier unprotected.
=> Remove use of RARRAY_PTR

ext/ffi_c/DynamicLibrary.c
On Windows FormatMessageA can return a NULL message - for example when trying to load a 32bit dll from a 64 bit program (garbage.so in the test suite). Since the passed in buffer contains junk data the resulting error message is made up of garbage characters which makes it impossible to know what the problem is.
This commit updates the message so that it always returns the error code (in this case 193) plus message, which makes it possible to debug the problem.
=> Windows - Update LoadLibrary Error Message to include Error Code

ext/ffi_c/DynamicLibrary.c
Free the message allocated by FormatMessageA (should have been included in the last commit).
=> Free Allocated Buffer

spec/ffi/fixtures/ClosureTest.c, spec/ffi/fixtures/PipeHelperWindows.c, spec/ffi/fixtures/PointerTest.c
This MR includes several small changes that enable MSVC 2022 to compile the libtest library in the spec/fixtures directory. With these changes, all tests pass on MSVC.
Note that the compile.rb file on Windows only works with mingw, so it would have to change to support MSVC. I assume that isn't important,  but if we wanted to go down that route at some point we could either:
*  add a Makefile for nmake like mkmf does
*  or likely better, and way more modern, add a simple CMakelists.text file and use cmake
=> MSVC Test Support

.github/workflows/ci.yml, lib/ffi/autopointer.rb, lib/ffi/managedstruct.rb, spec/ffi/managed_struct_spec.rb, spec/ffi/pointer_spec.rb, spec/ffi/spec_helper.rb
FFI users might not want to expose `release` as a public class method, but want to keep it private.
Also re-enable GC tests that were disabled as part of #427, but make them opt-in per env var `FFI_TEST_GC`.
Derivations of `Releaser` are no longer necessary, so that they are removed now.
=> Allow private release method for ManagedStruct and AutoPointer

ext/ffi_c/Struct.c, ext/ffi_c/Struct.h
It was introduced in commit 9d68c7f87ad7c869ee1ce3139269525af70e5df4 but moved to ruby code in commit 3f96bbb61b2f17ba9761a1d02745101a60cd26e1 . These fields are a leftover from the commit.
=> Remove no longer used StructField.get and .put

Rakefile, ext/ffi_c/extconf.rb, ext/ffi_c/libffi.bsd.mk, ext/ffi_c/libffi.darwin.mk, ext/ffi_c/libffi.gnu.mk
And allow to build binary gems for other platforms as well. Unfortunately there are issues on musl-based distros, so they are not yet enabled.
=> Update fat binary gems for Windows to ruby-3.2 and update libffi

Rakefile, ext/ffi_c/extconf.rb, ext/ffi_c/libffi.bsd.mk, ext/ffi_c/libffi.darwin.mk, ext/ffi_c/libffi.gnu.mk
It enables debug symbols and libffi assertions.
By default it is enabled for in-tree builds but `gem install` is not affected.
=> Add --enable-debug to extconf.rb which is called by 'rake compile'

ext/ffi_c/AbstractMemory.c, ext/ffi_c/Call.c, ext/ffi_c/Function.c, ext/ffi_c/FunctionInfo.c, ext/ffi_c/Struct.c
... and the declarations before statements, while being at it.
Fixes #1052
=> Avoid loop initial declarations for compat with Centos-7 

lib/ffi/types.rb, spec/ffi/struct_spec.rb
=> Avoid trying to store new DataConverter type in frozen TypeDefs hash

ext/ffi_c/Type.c
* Add missing `BUFFER_INOUT` and “missing” `LONGDOUBLE`
* Remove mentions of (legacy types?) `CALLBACK` and `CHAR_ARRAY` – they are not found in 1.16.3 even though chances are that they *are* supported by every computer
* Update `ARRAY`, `FUNCTION` and `STRUCT` to CamelCase and separate these class aliases from the `Type::Builtin` list
* Remove `MAPPED` – [`Mapped` has its own doc](https://rubydoc.info/gems/ffi/FFI/Type/Mapped)
* Clarify that, while all constants are exported to `Type`, the aliases aren’t found in `FFI` and `NativeType`
* This could rather be an oversight in the `A` macro
* Fix typos
* Avoid writing `(C)`, which instead renders to `©` ([rendered docs on `rubydoc.info`](https://rubydoc.info/gems/ffi/1.16.3/FFI/NativeType))
=> Update `NativeType` doc

ext/ffi_c/AbstractMemory.c, ext/ffi_c/ArrayType.c, ext/ffi_c/Buffer.c, ext/ffi_c/DynamicLibrary.c, ext/ffi_c/LastError.c, ext/ffi_c/MemoryPointer.c, ext/ffi_c/Pointer.c, ext/ffi_c/Struct.c, ext/ffi_c/StructLayout.c, ext/ffi_c/Type.c, lib/ffi/io.rb, lib/ffi/library.rb, lib/ffi/pointer.rb, lib/ffi/struct.rb, lib/ffi/struct_layout.rb, lib/ffi/struct_layout_builder.rb, lib/ffi/types.rb, spec/ffi/fixtures/compile.rb, spec/ffi/pointer_spec.rb
=> Replace `Fixnum` by `Integer` and use `Integer` instead of `Numeric` for offsets and sizes

ext/ffi_c/Pointer.c
So that other false and nil are treated as falsey and anything als as truthy.
=> Use RB_TEST for Pointer.autorelease=

ext/ffi_c/AbstractMemory.c
If `float64` are `Numeric`, surely `Integer` for `float32`s is even more misleading than `Numeric`?
=> Undo erroneous changes (#1064) of `Numeric`➡`Integer` for `AbstractMemory` `float32` R/W

ext/ffi_c/Pointer.c, spec/ffi/pointer_spec.rb
If you call FFI::Pointer#== with an instance of an object that is not FFI::Pointer or descendants an exception is thrown:
> "INTERNAL ERROR!!! TypeError: wrong argument type Module (expected FFI::Pointer).
In my case, this then causes the RubyMine debugger (debase) to blow up, making debugging harder.
This PR updates FFI::Pointer#== to return false if a pointer is compared to a non-pointer object, which is the expected behavior.
=> Update FFI::Pointer#== to not throw an exception

lib/ffi/function.rb, lib/ffi/library.rb
warning: instance variable @ffi_functions not initialized
=> Avoid warning about undefined wariables

.github/workflows/ci.yml, Gemfile, Rakefile, ext/ffi_c/libffi.darwin.mk, spec/env/Dockerfile.alpine, spec/env/Dockerfile.centos, spec/env/Dockerfile.debian, spec/ffi/callback_spec.rb, spec/ffi/library_spec.rb, spec/ffi/long_double_spec.rb
This adds binary gems for more platforms. Until now only Mingw platforms were provided. This PR adds many more platforms for Linux and Darwin on arm, x86 and x86_64 architectures. It also adds proper build tasks to CI and test tasks for binary gems on various platforms.
=> More platforms

spec/env/Dockerfile.alpine, spec/env/Dockerfile.centos, spec/env/Dockerfile.debian
To avoid development tools there.
=> CI: Avoid rbs install on multiarch tests

ext/ffi_c/Call.c, ext/ffi_c/Call.h, ext/ffi_c/Variadic.c
This could happen, when the Proc object created by rb_block_proc() is GC'ed before the call is executed. Practically this is very unlikely unless called with GC.stress=true .
It can easily be fixed, by returning the Proc object and keeping it in a local variable while the call is executed.
When running the test suite with GC.stress=true then it failed like so: Failures:
```
1) Callback struct by value parameter
Failure/Error:
LibTest.testCallbackTrV(s) do |struct|
s2[:s8] = struct[:s8]
s2[:f32] = struct[:f32]
s2[:s32] = struct[:s32]
end
NoMethodError:
undefined method `call' for an instance of FFI::MemoryPointer
./spec/ffi/callback_spec.rb:312:in `testCallbackTrV'
./spec/ffi/callback_spec.rb:312:in `block (2 levels) in <module:CallbackSpecs>'
2) Callback with  struct by reference argument …
```
=> Fix a very unlikely GC bug when using a callback block

.github/workflows/ci.yml
This is to avoid duplicated runs as soon as a pull request is opened. Please open a pull request to get the CI started!
=> CI: Run jobs on master branch and pull requests only

ext/ffi_c/StructLayout.c
When setting fields on layout in struct_layout_initialize which contain Ruby VALUEs, we must do so through the RB_OBJ_WRITE macro because it the class is declared as write-barrier protected.
Fixes #1079
=> Add missing write barriers to StructLayout#initialize

lib/ffi/autopointer.rb
It was never implemented since it doesn't work.
Fixes #1071
=> Remove AutoPointer.new with block from documentation

ext/ffi_c/AbstractMemory.c, sig/ffi/abstract_memory.rbs, spec/ffi/string_spec.rb
It was defined but not exposed to Ruby nor tested.
Fixes #1070
=> Add FFI::AbstractMemory#read_array_of_string

spec/ffi/spec_helper.rb
Ractor#take blocks sometimes infinitely on Ruby-3.3 on MINGW, but this seems unrelated to ffi.
=> CI: Exclude Ractor tests on Windows-Ruby-3.3

ext/ffi_c/Function.c, lib/ffi/ffi.rb, spec/ffi/async_callback_spec.rb, spec/ffi/fixtures/FunctionTest.c
If we don't do this, callbacks registered before fork will never actually fire after forking, and just hang forever.
We explicitly re-initialize the entire context (including re-initializing the mutexes and clearing out the list of callbacks), because:
* If a thread in the parent was in the process of calling a callback when we fork, the mutex would otherwise be "stuck on"
* I don't think we _want_ to actually execute any pending callbacks from other threads in the child process, so clearing the list makes sense anyway.
Fixes: https://github.com/ffi/ffi/issues/1114
=> Restart async callback dispatcher thread after fork

spec/ffi/fixtures/FunctionTest.c, spec/ffi/variadic_spec.rb
Kind of:
```
warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
va_start(args, c);
^
FunctionTest.c:79:59: note: parameter of type 'char' is declared here char testBlockingWRva(struct testBlockingData *self, char c, ...) {
^
```
=> Fix warning about va_start parameter in libtest raised by clang

spec/ffi/callback_spec.rb
Fiddle::Closures can't be used before process is forked, otherwise test suite might crash with SELinux. This is similar treatment as is used in [Fiddle](https://github.com/ruby/fiddle/commit/1343ac7a9567665affc0e9f4bc9fd74cfd97a5fd).
Fixes #1120
=> Ensure GC-ing closures before fork - 2nd attempt

sig/ffi/library.rbs
Error was `RBS::InvalidTypeApplication`:
Type `::FFI::DataConverter` is generic but used as a non generic type
at:
def typedef: [T < Type] (T old, Symbol | DataConverter add, ?untyped) -> T
DataConverter being a generic type, it needs type arguments, which in turn needs these generic type arguments declared beforehand for `typedef`.
This is extracted from https://github.com/ffi/ffi/pull/1108 .
=> Fix `FFI::DataConverter` non-generic usage

Gemfile, spec/env/Dockerfile.alpine, spec/env/Dockerfile.centos, spec/env/Dockerfile.debian
...since it will not be shipped with Ruby after Ruby 3.5.0.
I could see that this was a test-only dependency, so I added it to the "development" group of gems in the Gemfile.
https://github.com/search?q=repo%3Affi%2Fffi%20fiddle&type=code shows only hits in the spec directory.
=> Gemfile: depend on fiddle to avoid a Ruby warning

Gemfile, spec/ffi/function_spec.rb
This was broken since ruby commit
https://github.com/ruby/ruby/commit/d80f3a287c5c8d0404b6cb837db360cab320cde1
It shrinked shareability of Proc objects, so that we have to avoid a Proc here.
=> Fix making FFI::Function shareable for Ractor

samples/hello_ractor.rb, samples/qsort_ractor.rb, spec/ffi/async_callback_spec.rb, spec/ffi/dynamic_library_spec.rb, spec/ffi/enum_spec.rb, spec/ffi/errno_spec.rb, spec/ffi/function_spec.rb, spec/ffi/library_spec.rb, spec/ffi/platform_spec.rb, spec/ffi/spec_helper.rb, spec/ffi/struct_spec.rb, spec/ffi/variadic_spec.rb
Ractor#take was removed from ruby-3.5 since https://github.com/ruby/ruby/pull/13445
=> Use Ractor#value instead of deprecated #take
